#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SavePassword.Resource", IsApplication=true)]

namespace SavePassword
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_in_top = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_out_bottom = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int button_email_style = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int checkbox_style = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int edit_text_style = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_action_new = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_action_search = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000b
			public const int CreateAccountButton = 2131165195;
			
			// aapt resource value: 0x7f070010
			public const int btnPassword = 2131165200;
			
			// aapt resource value: 0x7f07000a
			public const int descriptionEditText = 2131165194;
			
			// aapt resource value: 0x7f070005
			public const int etSearch = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int listView = 2131165188;
			
			// aapt resource value: 0x7f070000
			public const int llContainer = 2131165184;
			
			// aapt resource value: 0x7f07000c
			public const int mainView = 2131165196;
			
			// aapt resource value: 0x7f070007
			public const int nameEditText = 2131165191;
			
			// aapt resource value: 0x7f070015
			public const int newAccount = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int newPasswordAction = 2131165206;
			
			// aapt resource value: 0x7f070008
			public const int passwordEditView = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int passwordRepeatEditView = 2131165193;
			
			// aapt resource value: 0x7f070014
			public const int search = 2131165204;
			
			// aapt resource value: 0x7f070006
			public const int textView1 = 2131165190;
			
			// aapt resource value: 0x7f070013
			public const int txtCreateDate = 2131165203;
			
			// aapt resource value: 0x7f070003
			public const int txtCreateDateHeader = 2131165187;
			
			// aapt resource value: 0x7f070011
			public const int txtName = 2131165201;
			
			// aapt resource value: 0x7f070001
			public const int txtNameHeader = 2131165185;
			
			// aapt resource value: 0x7f07000e
			public const int txtPassword = 2131165198;
			
			// aapt resource value: 0x7f070002
			public const int txtPasswordHeader = 2131165186;
			
			// aapt resource value: 0x7f070012
			public const int txtPasswordL = 2131165202;
			
			// aapt resource value: 0x7f07000f
			public const int txtRepeatPassword = 2131165199;
			
			// aapt resource value: 0x7f07000d
			public const int txtTitle = 2131165197;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Activity2 = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CreateAccount = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int row_account = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int actionbar = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
