#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SavePassword.Resource", IsApplication=true)]

namespace SavePassword
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_in_top = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_out_bottom = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int button_email_style = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int checkbox_style = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int edit_text_style = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_action_new = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_action_search = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int list_item_selector = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int market = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000b
			public const int CreateAccountButton = 2131230731;
			
			// aapt resource value: 0x7f080010
			public const int btnPassword = 2131230736;
			
			// aapt resource value: 0x7f08000a
			public const int descriptionEditText = 2131230730;
			
			// aapt resource value: 0x7f080005
			public const int etSearch = 2131230725;
			
			// aapt resource value: 0x7f080004
			public const int listView = 2131230724;
			
			// aapt resource value: 0x7f080000
			public const int llContainer = 2131230720;
			
			// aapt resource value: 0x7f08000c
			public const int mainView = 2131230732;
			
			// aapt resource value: 0x7f080007
			public const int nameEditText = 2131230727;
			
			// aapt resource value: 0x7f080015
			public const int newAccount = 2131230741;
			
			// aapt resource value: 0x7f080016
			public const int newPasswordAction = 2131230742;
			
			// aapt resource value: 0x7f080008
			public const int passwordEditView = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int passwordRepeatEditView = 2131230729;
			
			// aapt resource value: 0x7f080014
			public const int search = 2131230740;
			
			// aapt resource value: 0x7f080006
			public const int textView1 = 2131230726;
			
			// aapt resource value: 0x7f080013
			public const int txtCreateDate = 2131230739;
			
			// aapt resource value: 0x7f080003
			public const int txtCreateDateHeader = 2131230723;
			
			// aapt resource value: 0x7f080011
			public const int txtName = 2131230737;
			
			// aapt resource value: 0x7f080001
			public const int txtNameHeader = 2131230721;
			
			// aapt resource value: 0x7f08000e
			public const int txtPassword = 2131230734;
			
			// aapt resource value: 0x7f080002
			public const int txtPasswordHeader = 2131230722;
			
			// aapt resource value: 0x7f080012
			public const int txtPasswordL = 2131230738;
			
			// aapt resource value: 0x7f08000f
			public const int txtRepeatPassword = 2131230735;
			
			// aapt resource value: 0x7f08000d
			public const int txtTitle = 2131230733;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Activity2 = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CreateAccount = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int row_account = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int actionbar = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int CustomActionBarTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int MyActionBar = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
